joint_1:
  effective_angle: 324
  gear_ratio: 0.6470588235294118
  voltage_max: 10.5
  voltage_zero_angle: 5.2
joint_2:
  effective_angle: 324
  gear_ratio: 0.6470588235294118
  voltage_max: 10.5
  voltage_zero_angle: 5.2

