m0_controller:
  type: muscle_controllers/MuscleController
  name: m0
  pid: {p: 700,  i: 0.01, d: 100}
m1_controller:
  type: muscle_controllers/MuscleController
  name: m1
  pid: {p: 700,  i: 0.01, d: 100}
m2_controller:
  type: muscle_controllers/MuscleController
  name: m2
  pid: {p: 700,  i: 0.01, d: 100}
m3_controller:
  type: muscle_controllers/MuscleController
  name: m3
  pid: {p: 700,  i: 0.01, d: 100}
m4_controller:
  type: muscle_controllers/MuscleController
  name: m4
  pid: {p: 700,  i: 0.01, d: 100}
m5_controller:
  type: muscle_controllers/MuscleController
  name: m5
  pid: {p: 700,  i: 0.01, d: 100}
m6_controller:
  type: muscle_controllers/MuscleController
  name: m6
  pid: {p: 700,  i: 0.01, d: 100}
m7_controller:
  type: muscle_controllers/MuscleController
  name: m7
  pid: {p: 700,  i: 0.01, d: 100}
m8_controller:
  type: muscle_controllers/MuscleController
  name: m8
  pid: {p: 700,  i: 0.01, d: 100}
m9_controller:
  type: muscle_controllers/MuscleController
  name: m9
  pid: {p: 700,  i: 0.01, d: 100}
m10_controller:
  type: muscle_controllers/MuscleController
  name: m10
  pid: {p: 700,  i: 0.01, d: 100}
m11_controller:
  type: muscle_controllers/MuscleController
  name: m11
  pid: {p: 700,  i: 0.01, d: 100}
m12_controller:
  type: muscle_controllers/MuscleController
  name: m12
  pid: {p: 700,  i: 0.01, d: 100}
m13_controller:
  type: muscle_controllers/MuscleController
  name: m13
  pid: {p: 700,  i: 0.01, d: 100}
m14_controller:
  type: muscle_controllers/MuscleController
  name: m14
  pid: {p: 700,  i: 0.01, d: 100}
m15_controller:
  type: muscle_controllers/MuscleController
  name: m15
  pid: {p: 700,  i: 0.01, d: 100}
m16_controller:
  type: muscle_controllers/MuscleController
  name: m16
  pid: {p: 700,  i: 0.01, d: 100}
m17_controller:
  type: muscle_controllers/MuscleController
  name: m17
  pid: {p: 700,  i: 0.01, d: 100}
m18_controller:
  type: muscle_controllers/MuscleController
  name: m18
  pid: {p: 700,  i: 0.01, d: 100}
m19_controller:
  type: muscle_controllers/MuscleController
  name: m19
  pid: {p: 700,  i: 0.01, d: 100}
m20_controller:
  type: muscle_controllers/MuscleController
  name: m20
  pid: {p: 700,  i: 0.01, d: 100}
m21_controller:
  type: muscle_controllers/MuscleController
  name: m21
  pid: {p: 700,  i: 0.01, d: 100}
m22_controller:
  type: muscle_controllers/MuscleController
  name: m22
  pid: {p: 700,  i: 0.01, d: 100}
m23_controller:
  type: muscle_controllers/MuscleController
  name: m23
  pid: {p: 700,  i: 0.01, d: 100}
m24_controller:
  type: muscle_controllers/MuscleController
  name: m24
  pid: {p: 700,  i: 0.01, d: 100}
m25_controller:
  type: muscle_controllers/MuscleController
  name: m25
  pid: {p: 700,  i: 0.01, d: 100}
m26_controller:
  type: muscle_controllers/MuscleController
  name: m26
  pid: {p: 700,  i: 0.01, d: 100}
m27_controller:
  type: muscle_controllers/MuscleController
  name: m27
  pid: {p: 700,  i: 0.01, d: 100}
m28_controller:
  type: muscle_controllers/MuscleController
  name: m28
  pid: {p: 700,  i: 0.01, d: 100}
m29_controller:
  type: muscle_controllers/MuscleController
  name: m29
  pid: {p: 700,  i: 0.01, d: 100}
m30_controller:
  type: muscle_controllers/MuscleController
  name: m30
  pid: {p: 700,  i: 0.01, d: 100}
m31_controller:
  type: muscle_controllers/MuscleController
  name: m31
  pid: {p: 700,  i: 0.01, d: 100}
