min_acceptable_rt_loop_frequency: 990.0

publish_every_rt_jitter: false

using_raspberry_pi: false

muscle_list:
  - name: m0
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m1
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m2
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m3
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m4
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m5
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m6
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m7
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m8
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m9
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m10
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m11
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m12
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m13
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m14
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m15
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m16
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m17
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m18
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m19
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m20
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m21
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m22
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m23
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m24
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m25
    initial_value: 0.0
    activation_controller_port: 0
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m26
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m27
    initial_value: 0.0
    activation_controller_port: 1
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m28
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m29
    initial_value: 0.0
    activation_controller_port: 2
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m30
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 15
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
  - name: m31
    initial_value: 0.0
    activation_controller_port: 3
    activation_controller_channel: 7
    pressure_controller_port: 0
    pressure_controller_channel: 0
    tension_controller_port: 0
    tension_controller_channel: 0
